console.log(null == undefined);
console.log(null == NaN);
console.log(undefined == NaN);
console.log(NaN == NaN);
let a;
console.log(a == undefined);
console.log(a === undefined);
console.log(a == null);
console.log(a === null);
console.log(a);